sudo: required
sevices: docker
before_install:
  - docker-compose up --build -d

script:
  - docker-compose exac --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exac --env 'RAILS_ENV=test' web rails db:migrate
  - docker-compose exac --env 'RAILS_ENV=test' web rails db:test
